### ISSUE TITLE
Don't panic when missing env vars

### ISSUE THREAD

**Issue by cdahlhausen** [APTrust/preservation-services#10]
When executing go binaries without APT_CONFIG_DIR and APT_SERVICES_CONFIG env vars they panic and crash.

A common handling pattern of missing parameters would be to print the help. 

```
 APT_CONFIG_DIR=../ ./ingest_bucket_reader
panic: Required env var APT_SERVICES_CONFIG not set

goroutine 1 [running]:
github.com/APTrust/preservation-services/models/common.getRequiredEnvVar(0x17b4937, 0x13, 0xc00002200f, 0x3)
	/Users/cd3ef/aptrust/preservation-services/models/common/config.go:183 +0xf9
github.com/APTrust/preservation-services/models/common.getEnvVars(0x100bbfc, 0x2876540, 0x8, 0x1014337)
	/Users/cd3ef/aptrust/preservation-services/models/common/config.go:176 +0x67
github.com/APTrust/preservation-services/models/common.loadConfig(0xc000179e38)
	/Users/cd3ef/aptrust/preservation-services/models/common/config.go:83 +0x37
github.com/APTrust/preservation-services/models/common.NewConfig(0x20)
	/Users/cd3ef/aptrust/preservation-services/models/common/config.go:74 +0x22
github.com/APTrust/preservation-services/models/common.NewContext(0x0)
	/Users/cd3ef/aptrust/preservation-services/models/common/context.go:27 +0x34
github.com/APTrust/preservation-services/workers.NewIngestBucketReader(...)
	/Users/cd3ef/aptrust/preservation-services/workers/ingest_bucket_reader.go:23
main.main()
	/Users/cd3ef/aptrust/preservation-services/apps/ingest_bucket_reader/ingest_bucket_reader.go:27 +0x97
```

**Comment by cdahlhausen** [comment]
It may also make sense to supply default values. APT_CONFIG_DIR maybe the current working directory ```./```

**Comment by diamondap** [comment]
Should be fixed in https://github.com/APTrust/preservation-services/commit/b4af44b7ba7d6f994ccad3d9aceea83393368108

**Comment by cdahlhausen** [comment]
Confirmed. Fixed.
